[package]
name = "day_22"
version = "0.1.0"
edition = "2018"

# https://doc.rust-lang.org/cargo/reference/features.html

[features]
bounded_map = []          # optimisation to restrict search within some bounds
default = ["bounded_map"]

[dependencies]
